[
    [
        "mainmenu",
        "music",
        "background",
        "special://home/media/menubg/music.jpg"
    ],
    [
        "mainmenu",
        "music",
        "backgroundName",
        "Music"
    ],
    [
        "mainmenu",
        "music",
        "icon",
        "special://skin/extras/icons/DefaultAudio.png"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "thumb",
        "image://C%3a%5cUsers%5cmarkd%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.jellycon%5cicon.png/"
    ],
    [
        "mainmenu",
        "tvshows",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetName",
        "Trakt - My Lists"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPath",
        "plugin://plugin.video.silvolists/"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetStyle",
        "Panel"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetCase",
        "Glass"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetArt",
        "Poster"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetBack",
        "Default"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetTitle",
        "Panel"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPanelInfo",
        "true"
    ],
    [
        "mainmenu",
        "tvshows",
        "background",
        "special://home/media/menubg/tvshows.jpg"
    ],
    [
        "mainmenu",
        "tvshows",
        "backgroundName",
        "TV Shows"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "special://skin/extras/icons/DefaultTVShows.png"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.jellycon/?url=/Users/%7Buserid%7D/Items%3FFields%3DDateCreated%252CEpisodeCount%252CSeasonCount%252CPath%252CGenres%252CStudios%252CEtag%252CTaglines%252CSortName%252CRecursiveItemCount%252CChildCount%252CProductionLocations%252CCriticRating%252COfficialRating%252CCommunityRating%252CPremiereDate%252CProductionYear%252CAirTime%252CStatus%252CTags%252CMediaStreams%252COverview%26ImageTypeLimit%3D1%26IsMissing%3DFalse%26IncludeItemTypes%3DSeries%26Recursive%3DTrue%26ParentId%3Da656b907eb3a73532e40e44b968d0225%26format%3Djson&mode=GET_CONTENT&media_type=tvshows\",return)"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.jellycon/?url=/Users/%7Buserid%7D/Items%3FFields%3DDateCreated%252CEpisodeCount%252CSeasonCount%252CPath%252CGenres%252CStudios%252CEtag%252CTaglines%252CSortName%252CRecursiveItemCount%252CChildCount%252CProductionLocations%252CCriticRating%252COfficialRating%252CCommunityRating%252CPremiereDate%252CProductionYear%252CAirTime%252CStatus%252CTags%252CMediaStreams%252COverview%26ImageTypeLimit%3D1%26IsMissing%3DFalse%26IncludeItemTypes%3DSeries%26Recursive%3DTrue%26ParentId%3Da656b907eb3a73532e40e44b968d0225%26format%3Djson&mode=GET_CONTENT&media_type=tvshows\",return)"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetName",
        "JellyCon - Shows - Show All"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetPath",
        "plugin://plugin.video.jellycon/?url=/Users/%7Buserid%7D/Items%3FFields%3DDateCreated%252CEpisodeCount%252CSeasonCount%252CPath%252CGenres%252CStudios%252CEtag%252CTaglines%252CSortName%252CRecursiveItemCount%252CChildCount%252CProductionLocations%252CCriticRating%252COfficialRating%252CCommunityRating%252CPremiereDate%252CProductionYear%252CAirTime%252CStatus%252CTags%252CMediaStreams%252COverview%26ImageTypeLimit%3D1%26IsMissing%3DFalse%26IncludeItemTypes%3DSeries%26Recursive%3DTrue%26ParentId%3Da656b907eb3a73532e40e44b968d0225%26format%3Djson&mode=GET_CONTENT&media_type=tvshows&reload=$INFO[Window(Home).Property(widgetreload-episodes)]"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetStyle",
        "Extended Panel"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetCase",
        "Glass"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetArt",
        "FanArt"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetBack",
        "Default"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetTitle",
        "Panel"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "widgetPanelInfo",
        "false"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.jellycon/?url=/Users/%7Buserid%7D/Items%3FFields%3DDateCreated%252CEpisodeCount%252CSeasonCount%252CPath%252CGenres%252CStudios%252CEtag%252CTaglines%252CSortName%252CRecursiveItemCount%252CChildCount%252CProductionLocations%252CCriticRating%252COfficialRating%252CCommunityRating%252CPremiereDate%252CProductionYear%252CAirTime%252CStatus%252CTags%252CMediaStreams%252COverview%26ImageTypeLimit%3D1%26IsMissing%3DFalse%26IncludeItemTypes%3DSeries%26Recursive%3DTrue%26ParentId%3Da656b907eb3a73532e40e44b968d0225%26format%3Djson&mode=GET_CONTENT&media_type=tvshows\",return)"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "background",
        "special://home/media/menubg/jellyfintv.jpg"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "backgroundName",
        "Jellyfin TV"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "thumb",
        "special://home/addons/plugin.video.jellycon/icon.png"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "thumb",
        "special://home/addons/plugin.video.jellycon/icon.png"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "jellyfintv",
        "thumb",
        "special://home/addons/plugin.video.jellycon/icon.png"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "icon",
        "special://skin/extras/icons/DefaultAddonPVRClient.png"
    ],
    [
        "mainmenu",
        "31957",
        "background",
        "special://home/media/menubg/addons.jpg"
    ],
    [
        "mainmenu",
        "31957",
        "backgroundName",
        "Addons"
    ],
    [
        "mainmenu",
        "31957",
        "icon",
        "special://skin/extras/icons/DefaultAddon.png"
    ],
    [
        "mainmenu",
        "13000",
        "background",
        "special://home/media/menubg/settings.jpg"
    ],
    [
        "mainmenu",
        "13000",
        "backgroundName",
        "Settings"
    ],
    [
        "mainmenu",
        "13000",
        "icon",
        "special://skin/extras/icons/DefaultAddonService.png"
    ],
    [
        "mainmenu",
        "33060",
        "background",
        "special://home/media/menubg/power.jpg"
    ],
    [
        "mainmenu",
        "33060",
        "backgroundName",
        "Power"
    ],
    [
        "mainmenu",
        "33060",
        "icon",
        "special://skin/extras/icons/power.png"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.silvomovies/\",return)"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetName",
        "New Movies"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetType",
        "movies"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetPath",
        "plugin://plugin.video.jellycon/?url=/Users/%7Buserid%7D/Items%3FIncludeItemTypes%3DMovie%26CollapseBoxSetItems%3DTrue%26GroupItemsIntoCollections%3DTrue%26Recursive%3DTrue%26IsMissing%3DFalse%26Fields%3DDateCreated%252CEpisodeCount%252CSeasonCount%252CPath%252CGenres%252CStudios%252CEtag%252CTaglines%252CSortName%252CRecursiveItemCount%252CChildCount%252CProductionLocations%252CCriticRating%252COfficialRating%252CCommunityRating%252CPremiereDate%252CProductionYear%252CAirTime%252CStatus%252CTags%252CMediaStreams%252COverview%26ImageTypeLimit%3D1%26SortBy%3DDateCreated%26SortOrder%3DDescending%26ParentId%3Dc2257bbd84a4b4bb4f9f4e16cd641326%26format%3Djson&mode=GET_CONTENT&media_type=movies"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetStyle",
        "Extended Panel"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetArt",
        "Poster"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "widgetCase",
        "Case"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "background",
        "special://home/media/menubg/movies.jpg"
    ],
    [
        "mainmenu",
        "plugin.video.silvomovies/",
        "backgroundName",
        "Movies"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widget",
        "library"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetName",
        "Favourites"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetType",
        "favourite"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetPath",
        "favourites://"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetStyle",
        "Panel"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetCase",
        "Glass"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetArt",
        "Square Poster"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetBack",
        "Default"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetTitle",
        "Panel"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "widgetPanelInfo",
        "false"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "background",
        "special://home/media/menubg/livetv.jpg"
    ],
    [
        "mainmenu",
        "plugin.video.silvolivetv/",
        "backgroundName",
        "Live TV"
    ]
]